FROM registry.lab.example.com:8443/ubi10/nodejs-22:latest as builder
ADD . .
# Avoid using "npm ci" to prevent problems with the private NPM registry in the lab environment
RUN npm install --omit dev

FROM registry.lab.example.com:8443/ubi10/nodejs-22:latest
COPY --from=builder . .
EXPOSE 3000
CMD npm run -d start
