FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:1-51

# Use root user to listen on port 80
USER root


# Application listens on this port
ENV PORT=80
EXPOSE ${PORT}

# Install application dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# Copy the application source code
COPY . .

# Run the server
CMD npm start
