

redis:
 redis_password: very-strong
 database_service_name: quotes-store
 redis_version: "1-64"

quotes:
  image: registry.lab.example.com:8443/redhattraining/ocpdev-redis-quotes:4.22
  import:
    enabled: true
