{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "openshift.io/generated-by": "OpenShiftNewApp"
        },
        "creationTimestamp": null,
        "labels": {
            "app": "hello-s2i"
        },
        "name": "hello-s2i",
        "selfLink": "/api/v1/namespaces/lutfio-garantibbva-com-tr-apache-s2i/services/hello-s2i"
    },
    "spec": {
        "ports": [
            {
                "name": "8080-tcp",
                "port": 8080,
                "protocol": "TCP",
                "targetPort": 8080
            }
        ],
        "selector": {
            "app": "hello-s2i",
            "deploymentconfig": "hello-s2i"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
