pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
	// some comment
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
	label 'master'
      }
    }

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
	stage('stage2') {
	steps {
	sh 'echo hello from stage2!'
		}
	}
	
	stage('manual approval') {
	steps {
	timeout(time: 60, unit: 'MINUTES') {
		input message: "Move to Stage 3?"
	}
	}
	}

        // TODO: ADD A STAGE THAT SAYS HELLO

	// test
        // TODO: ADD AN APPROVAL STAGE

        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
