apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: expense
      app.kubernetes.io/component: expense
      app.kubernetes.io/instance: expense
    name: expense
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: quay.io/redhattraining/ocpdev-expense-service:4.12
      from:
        kind: DockerImage
        name: quay.io/redhattraining/ocpdev-expense-service:4.12
      generation: null
      importPolicy: {}
      name: "4.12"
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"expense:4.12"},"fieldPath":"spec.template.spec.containers[?(@.name==\"expense\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: expense
      app.kubernetes.io/component: expense
      app.kubernetes.io/instance: expense
    name: expense
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: expense
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: expense
      spec:
        containers:
        - image: ' '
          name: expense
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              memory: "256Mi"
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: expense
      app.kubernetes.io/component: expense
      app.kubernetes.io/instance: expense
    name: expense
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: expense
  status:
    loadBalancer: {}
kind: List
metadata: {}
