postgres:
  user: "dbuser"
  pass: "mypass"
  db: "sampledb"

expenseService:
  replicaCount: 1
  image: "registry.lab.example.com:8443/redhattraining/ocpdev-expense-service:4.22"
  host: "expense-service"
  domain: "apps.lab.example.com"
