FROM registry.access.redhat.com/ubi9/nodejs-16:1-120 as builder
# USER root
ADD . $HOME
# Avoid using "npm ci" to prevent problems with the private NPM registry in the lab environment
RUN npm install --omit dev

FROM registry.access.redhat.com/ubi9/nodejs-16-minimal:1-130
COPY --from=builder $HOME $HOME
EXPOSE 3000
CMD npm run -d start
