FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:1-51 as builder
ADD . .

# Allow the root group to have the same permissions as the root user
# in the application directory
USER root
RUN chgrp -R 0 . && \
    chmod -R g=u .
USER default

# Avoid using "npm ci" to prevent problems with the private NPM registry in the lab environment
RUN npm install --omit dev

FROM registry.access.redhat.com/ubi9/nodejs-18-minimal:1-51
COPY --from=builder $HOME $HOME
EXPOSE 3000
CMD npm run -d start
