apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  workspaces:
    # TODO
  params:
    # TODO
  steps:
    - name: build
      # TODO
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
