# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

#change the port to 8080
EXPOSE 8080

#change port listen from 80 to 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

#change permission to allow run container on openshift (rootless)
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && chmod -R g=u /var/log/httpd /var/run/httpd

#Run as a non-privileged user(rootless)
USER 1001
