FROM registry.ocp4.example.com:8443/ubi8/nodejs-16 AS appbuild

LABEL version="1.0"
LABEL description="To Do List application builder"

# ENV REACT_APP_API_HOST=http://localhost:3000
ENV REACT_APP_API_HOST=""

USER 0

ADD . .

RUN chgrp -R 0 . && \
  chmod -R g=u . && \
  npm install --no-package-lock && \
  npm run build

# https://github.com/sclorg/nginx-container
FROM registry.ocp4.example.com:8443/ubi8/nginx-118

LABEL version="1.0"
LABEL description="To Do List application front-end"
LABEL creationDate="2017-12-25"
LABEL updatedDate="2021-05-19"

COPY nginx.conf /etc/nginx
COPY --from=appbuild /opt/app-root/src/build /usr/share/nginx/html

EXPOSE 8080
USER nginx

CMD nginx -g "daemon off;"
